name: mailscan

services:
  stalwart:
    image: stalwartlabs/mail-server:latest
    ports: 
      - "443:443"
      - "7070:8080"
      - "25:25"
      - "587:587" 
      - "465:465"
      - "143:143" 
      - "993:993" 
      - "4190:4190"
    networks:
      net:
        ipv4_address: 172.16.0.5
    volumes:
      - type: bind
        source: ./stalwart-mail
        target: /opt/stalwart-mail

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    networks:
      net:
        ipv4_address: 172.16.0.6
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-topics:
    image: apache/kafka:latest
    command: >
        bash -c "/opt/kafka/bin/kafka-topics.sh --create --topic mails --bootstrap-server broker:9092 
        && /opt/kafka/bin/kafka-topics.sh --create --topic summary --bootstrap-server broker:9092"
    depends_on: 
      - broker
    networks:
      net:
        ipv4_address: 172.16.0.7

#  kafka-reader:
#    image: apache/kafka:latest
#    command: /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server broker:9092 --topic mails
#    depends_on:
#      kafka-topics:
#        condition: service_completed_successfully
#    networks:
#      net:
#        ipv4_address: 172.16.0.8

  logstash:
    build: ./logstash
    networks:
      net:
        ipv4_address: 172.16.0.9
    stdin_open: true
    tty: true
    environment:
      MAIL_USR_PSW_FILE: /run/secrets/mail_usr_psw
      LOGSTASH_KEYSTORE_FILE: /run/secrets/logstash_keystore_pass
    secrets:
      - mail_usr_psw
      - logstash_keystore_pass
    depends_on:
      kafka-topics:
        condition: service_completed_successfully

  # flink-jobmanager:
  #   image: flink:latest
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - net
  #   hostname: jobmanager
  #   environment:
  #     FLINK_PROPERTIES: 'jobmanager.rpc.address: jobmanager'
  #   command: standalone-job --job-classname org.dmi.mailscanner.DataStreamJob
  #   volumes:
  #     - /home/simoneb/Work/tap/project/flink/mailscanner/target:/opt/flink/usrlib

  # flink-taskmanager:
  #   image: flink:latest
  #   networks:
  #     - net
  #   environment:
  #     FLINK_PROPERTIES: 'jobmanager.rpc.address: jobmanager'
  #   depends_on:
  #     - flink-jobmanager
  #   command: taskmanager
  #   volumes:
  #     - /home/simoneb/Work/tap/project/flink/mailscanner/target:/opt/flink/usrlibs

  pyflink:
    build: ./flink/pyflink
    networks:
      - net
    ports:
      - 8081:8081

  redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    ports: 
      - 8080:8080
    networks:
      - net
    environment:
     KAFKA_BROKERS: broker:9092

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16

secrets:
  mail_usr_psw:
    file: ./secrets/user-password
  logstash_keystore_pass:
    file: ./secrets/logstash-keystore
